// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAllCountsFromToday():Promise<Array<models.Count>>;

export function Increment(arg1:string,arg2:number):Promise<models.Count>;
