// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCountsByKey(arg1) {
  return window['go']['services']['CounterService']['GetAllCountsByKey'](arg1);
}

export function Increment(arg1) {
  return window['go']['services']['CounterService']['Increment'](arg1);
}
