// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCountsFromToday() {
  return window['go']['services']['CounterService']['GetAllCountsFromToday']();
}

export function Increment(arg1, arg2) {
  return window['go']['services']['CounterService']['Increment'](arg1, arg2);
}
