// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function EnsurePrinterReady(arg1:string):Promise<void>;

export function GetInstalledPrinters():Promise<Array<string>>;

export function GetPrinterStatus(arg1:string):Promise<string>;

export function PrintReport(arg1:models.Report,arg2:string):Promise<void>;

export function PrintTicket(arg1:models.Ticket,arg2:string):Promise<void>;

export function PrintTickets(arg1:Array<models.Ticket>,arg2:string):Promise<void>;

export function Startup():Promise<void>;
