// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsurePrinterReady(arg1) {
  return window['go']['services']['PrintService']['EnsurePrinterReady'](arg1);
}

export function GetInstalledPrinters() {
  return window['go']['services']['PrintService']['GetInstalledPrinters']();
}

export function GetPrinterStatus(arg1) {
  return window['go']['services']['PrintService']['GetPrinterStatus'](arg1);
}

export function PrintReport(arg1, arg2) {
  return window['go']['services']['PrintService']['PrintReport'](arg1, arg2);
}

export function PrintTicket(arg1, arg2) {
  return window['go']['services']['PrintService']['PrintTicket'](arg1, arg2);
}

export function PrintTickets(arg1, arg2) {
  return window['go']['services']['PrintService']['PrintTickets'](arg1, arg2);
}

export function Startup() {
  return window['go']['services']['PrintService']['Startup']();
}
