// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfThereIsAnOpenOrPendingReport() {
  return window['go']['services']['ReportService']['CheckIfThereIsAnOpenOrPendingReport']();
}

export function PartialCloseReport(arg1, arg2) {
  return window['go']['services']['ReportService']['PartialCloseReport'](arg1, arg2);
}

export function StartReport(arg1) {
  return window['go']['services']['ReportService']['StartReport'](arg1);
}

export function TotalCloseReport(arg1, arg2) {
  return window['go']['services']['ReportService']['TotalCloseReport'](arg1, arg2);
}
