// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRoute(arg1:models.Route):Promise<void>;

export function DeleteRoute(arg1:models.Route):Promise<void>;

export function GetRoutes():Promise<Array<models.Route>>;

export function UpdateRoute(arg1:models.Route):Promise<void>;
