// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoute(arg1) {
  return window['go']['services']['RouteService']['AddRoute'](arg1);
}

export function DeleteRoute(arg1) {
  return window['go']['services']['RouteService']['DeleteRoute'](arg1);
}

export function GetRoutes() {
  return window['go']['services']['RouteService']['GetRoutes']();
}

export function UpdateRoute(arg1) {
  return window['go']['services']['RouteService']['UpdateRoute'](arg1);
}
