// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAppSettings():Promise<models.AppSettings>;

export function SaveAppSettings(arg1:models.AppSettings):Promise<models.AppSettings>;
