// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SyncRoutes() {
  return window['go']['services']['SyncService']['SyncRoutes']();
}

export function SyncUsers() {
  return window['go']['services']['SyncService']['SyncUsers']();
}
