// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTicket(arg1) {
  return window['go']['services']['TicketService']['AddTicket'](arg1);
}

export function DeleteTickets(arg1) {
  return window['go']['services']['TicketService']['DeleteTickets'](arg1);
}

export function UpdateTickets(arg1) {
  return window['go']['services']['TicketService']['UpdateTickets'](arg1);
}
